songwrytrproject/songwrytrapp/urls.py
from django.urls import include, path
from .views import *

app_name = "songwrytrapp"

urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls'), name='login'),
    path('accounts/register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('writers/', writer_list, name='writers'),
    path('writer/form', writer_form, name='writer_form'),
    path('writers/<int:writer_id>/form/', writer_edit_form, name='writer_edit_form'),
    path('writers/<int:writer_id>/', writer_details, name='writer'),
    path('publishingcompanies/', publishingcompany_list, name='publishingcompanies'),
    path('publishingcompany/form', publishingcompany_form, name='publishingcompany_form'),
    path('publishingcompanies/<int:publishingcompany_id>/form/', publishingcompany_edit_form, name='publishingcompany_edit_form'),
    path('publishingcompanies/<int:publishingcompany_id>/', publishingcompany_details, name='publishingcompany'),
    path('compositions/', composition_list, name='compositions'),
    path('composition/form', composition_form, name='composition_form'),
    path('compositions/<int:composition_id>/form/', composition_edit_form, name='composition_edit_form'),
    path('compositions/<int:composition_id>/', composition_details, name='composition'),
    path('compositions/<int:composition_id>/attachwriter/', composition_writer_form, name='composition_writer_form'),
    path('compositions/<int:composition_id>/writer/<int:compositionwriter_id>', composition_writer_edit_form, name='composition_writer_edit_form'),
    path('compositions/<int:composition_id>/attachpublisher/', composition_publishing_form, name='composition_publishing_form'),
    path('compositions/<int:composition_id>/publishing/<int:compositionpublishing_id>', composition_publishing_edit_form, name='composition_publishing_edit_form'),
    path('compositions/<int:composition_id>/removewriter/<int:compositionwriter_id>', composition_writer_remove, name='composition_writer_remove'),
    path('compositions/<int:composition_id>/removepublisher/<int:compositionpublishing_id>', composition_publishing_remove, name='composition_publishing_remove'),
    path('compositions/<int:composition_id>/recording/', composition_recording_form, name='composition_recording_form'),
    path('compositions/<int:composition_id>/recording/<int:recording_id>', composition_recording_edit_form, name='composition_recording_edit_form'),
    path('compositions/<int:composition_id>/recording/<int:recording_id>/', composition_recording_delete, name='composition_recording_delete'),
]

songwrytrproject/songwrytrproject/urls.py
from django.contrib import admin
from django.urls import include, path
from songwrytrapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('songwrytrapp.urls')),
]

songwrytrproject/songwrytrapp/models/composition.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Composition(models.Model):

    user = models.ForeignKey(User, verbose_name=("compositions"), on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    alt_titles = models.CharField(max_length=255)
    lyrics = models.TextField()
    notes = models.CharField(max_length=255)
    date_created = models.DateField(auto_now=False, auto_now_add=False)

    class Meta:
        verbose_name = ("composition")
        verbose_name_plural = ("compositions")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("composition_detail", kwargs={"pk": self.pk})

songwrytrproject/songwrytrapp/models/compositionPublishing.py
from django.db import models
from django.urls import reverse
from .publishingCompany import PublishingCompany
from .composition import Composition

class CompositionPublishing(models.Model):

    composition = models.ForeignKey(Composition, on_delete=models.CASCADE)
    publishing_company = models.ForeignKey(PublishingCompany, on_delete=models.CASCADE)
    percentage = models.DecimalField(max_digits=5, decimal_places=2)
    pro_work_num = models.IntegerField()

    class Meta:
        verbose_name = ("compositionpublishing")
        verbose_name_plural = ("compositionpublishings")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("compositionpublishing_detail", kwargs={"pk": self.pk})

songwrytrproject/songwrytrapp/models/compositionWriter.py
from django.db import models
from django.urls import reverse
from .composition import Composition
from .writer import Writer

class CompositionWriter(models.Model):

    writer = models.ForeignKey(Writer, on_delete=models.CASCADE)
    composition = models.ForeignKey(Composition, on_delete=models.CASCADE)
    percentage = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        verbose_name = ("compositionwriter")
        verbose_name_plural = ("compositionwriters")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("compositionwriter_detail", kwargs={"pk": self.pk})

songwrytrproject/songwrytrapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

songwrytrproject/songwrytrapp/models/pro.py
from django.db import models
from django.urls import reverse

class PRO(models.Model):

    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=50)
    website = models.CharField(max_length=255)

    class Meta:
        verbose_name = ("pro")
        verbose_name_plural = ("pros")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("pro_detail", kwargs={"pk": self.pk})

songwrytrproject/songwrytrapp/models/publishingCompany.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .pro import PRO

class PublishingCompany(models.Model):

    user = models.ForeignKey(User, verbose_name=("publishingcompanies"), on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    admin = models.CharField(max_length=255, null=True, blank=True)
    pro = models.ForeignKey(PRO, on_delete=models.CASCADE)
    pro_acct_num = models.IntegerField()

    class Meta:
        verbose_name = ("publishingcompany")
        verbose_name_plural = ("publishingcompanies")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("publishingcompany_detail", kwargs={"pk": self.pk})

songwrytrproject/songwrytrapp/models/recording.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .composition import Composition

class Recording(models.Model):

    user = models.ForeignKey(User, verbose_name=("recordings"), on_delete=models.CASCADE)
    audio_url = models.CharField(max_length=255)
    producer = models.CharField(max_length=50)
    artist = models.CharField(max_length=50)
    recording_type = models.CharField(max_length=50)
    date_recorded = models.DateField(auto_now=False, auto_now_add=False)
    is_mixed = models.BooleanField(default="off")
    is_mastered = models.BooleanField(default="off")
    is_delivered = models.BooleanField(default="off")
    composition = models.ForeignKey(Composition, on_delete=models.CASCADE)
    image_url = models.CharField(max_length=255)
    ownership_split = models.CharField(max_length=255)

    class Meta:
        verbose_name = ("recording")
        verbose_name_plural = ("recordings")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("recording_detail", kwargs={"pk": self.pk})

songwrytrproject/songwrytrapp/models/writer.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .pro import PRO

class Writer(models.Model):

    user = models.ForeignKey(User, verbose_name=("writers"), on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    publishing_notes = models.CharField(max_length=255)
    pro = models.ForeignKey(PRO, on_delete=models.CASCADE)
    pro_ipi = models.IntegerField()

    class Meta:
        verbose_name = ("writer ")
        verbose_name_plural = ("writers")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("writer_detail", kwargs={"pk": self.pk})

songwrytrproject/songwrytrapp/views/connection.py
class Connection:
    db_path = "/Users/landonmorgan/workspace/backend/songwrytr/songwrytrproject/db.sqlite3"
    # be sure to replace path with absolute path to your db.sqlite3 file

songwrytrproject/songwrytrapp/views/home.py
import sqlite3
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from songwrytrapp.models import Recording, Composition, CompositionWriter, CompositionPublishing, model_factory
from .connection import Connection

def get_recent_recordings(request):
    with sqlite3.connect(Connection.db_path) as conn:
        conn.row_factory = model_factory(Recording)
        user_id = request.user.id
        db_cursor = conn.cursor()
        db_cursor.execute("""
        SELECT
            r.user_id,
            r.audio_url,
            r.producer,
            r.artist,
            r.recording_type,
            r.date_recorded,
            r.composition_id,
            r.image_url,
            r.is_mixed,
            r.is_mastered,
            r.is_delivered,
            c.title,
            STRFTIME('%m/%d/%Y',r.date_recorded) as date_refactored
        FROM songwrytrapp_composition c
        JOIN songwrytrapp_recording r
        ON r.composition_id = c.id
        WHERE r.user_id = ?
        ORDER BY r.date_recorded DESC
        LIMIT 5
        """, (user_id,))

        return db_cursor.fetchall()

def get_recent_compositions(request):
    with sqlite3.connect(Connection.db_path) as conn:
        conn.row_factory = model_factory(Composition)
        user_id = request.user.id
        db_cursor = conn.cursor()
        db_cursor.execute("""
        SELECT
            c.id,
            c.title,
            STRFTIME('%m/%d/%Y',c.date_created) as date_refactored,
            c.user_id
        FROM songwrytrapp_composition c
        WHERE c.user_id = ?
        ORDER BY c.date_created DESC
        LIMIT 5
        """, (user_id,))

        return db_cursor.fetchall()

def get_all_composition_writers(request):
    with sqlite3.connect(Connection.db_path) as conn:
        conn.row_factory = model_factory(CompositionWriter)
        user_id = request.user.id
        db_cursor = conn.cursor()
        db_cursor.execute("""
        SELECT
            cw.id,
            cw.writer_id,
            cw.composition_id,
            w.user_id,
            w.first_name,
            w.last_name
        FROM songwrytrapp_compositionwriter cw
        JOIN songwrytrapp_writer w
        ON w.id = cw.writer_id
        WHERE w.user_id = ?
        """, (user_id,))

        return db_cursor.fetchall()

def get_all_composition_publishing(request):
    with sqlite3.connect(Connection.db_path) as conn:
        conn.row_factory = model_factory(CompositionPublishing)
        user_id = request.user.id
        db_cursor = conn.cursor()
        db_cursor.execute("""
        SELECT
            cp.id,
            cp.publishing_company_id,
            cp.composition_id,
            pc.user_id,
            pc.name
        FROM songwrytrapp_compositionpublishing cp
        JOIN songwrytrapp_publishingcompany pc
        ON pc.id = cp.publishing_company_id
        WHERE pc.user_id = ?
        """, (user_id,))

        return db_cursor.fetchall()

@login_required
def home(request):
    if request.method == 'GET':
        recent_recordings = get_recent_recordings(request)
        recent_compositions = get_recent_compositions(request)
        all_composition_writers = get_all_composition_writers(request)
        all_composition_publishing = get_all_composition_publishing(request)
        template = 'home.html'
        context = {
            'recent_recordings': recent_recordings,
            'recent_compositions': recent_compositions,
            'all_composition_writers': all_composition_writers,
            'all_composition_publishing': all_composition_publishing
        }

        return render(request, template, context)

songwrytrproject/songwrytrapp/templates/compositions/detail.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/compositions.css' %}" />
{% endblock %}

{% block navbar %}
    {% if request.user.id %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'songwrytrapp:home'%}"><img src="{% static "img/songwrytr_logo_sm.png" %}" alt="SONGWRYTR" height="50px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songwrytrapp:writers' %}">Writers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'songwrytrapp:compositions' %}">Compositions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songwrytrapp:publishingcompanies' %}">Publishing</a>
                    </li>
                </ul>
                <a class="form-inline my-2 my-lg-0" href="{% url 'songwrytrapp:logout' %}">Logout</a>
            </div>
        </nav>
    {% endif %}
{% endblock %}

{% block content %}
  {% if request.user.id == composition.user_id %}
    <h1>"{{ composition.title }}"</h1>
    <div class="details-buttons">
      <div class="detail-button">
        <form action="{% url 'songwrytrapp:composition_edit_form' composition.id %}" method="GET"> 
            {% csrf_token %}
            <button>Edit</button>
        </form>
      </div>
      <div class="detail-button">
        <form action="{% url 'songwrytrapp:composition' composition.id %}" method="POST" onsubmit="return ConfirmDeleteComposition()">
          {% csrf_token %}
          <input type="hidden" name="actual_method" value="DELETE">
          <button>Delete</button>
        </form>
      </div>
    </div>
    {% if composition.alt_titles or composition.date_created or composition.notes %}
      <div class="wrap-collabsible">
        <input id="collapsible1" class="toggle" type="checkbox">
        <label for="collapsible1" class="lbl-toggle">Composition Details</label>
        <div class="collapsible-content">
          <div class="content-inner">
            {% if composition.alt_titles %}
              <div>Alternate Titles: {{ composition.alt_titles }}</div>
            {% endif %}
            {% if composition.date_created %}
              <div>Date Created: {{ composition.date_refactored }}</div>
            {% endif %}
            {% if composition.notes %}
              <div>Notes: {{ composition.notes|linebreaksbr }}</div>
            {% endif %}
        </div>
      </div>
    </div>
    {% endif %}
    {% if composition.lyrics %}
      <div class="wrap-collabsible">
        <input id="collapsible2" class="toggle" type="checkbox">
        <label for="collapsible2" class="lbl-toggle">Lyrics</label>
        <div class="collapsible-content">
          <div class="content-inner">
            <div class="indent">{{ composition.lyrics|linebreaks }}</div>
          </div>
        </div>
      </div>
    {% endif %}
    <div class="wrap-collabsible">
      <input id="collapsible3" class="toggle" type="checkbox">
      <label for="collapsible3" class="lbl-toggle">Writer Share</label>
      <div class="collapsible-content">
        <div class="content-inner">
          <div style="list-style: none;">
            {% for writer in composition_writers %}
              {% if request.user.id == writer.user_id %}
                <div class="cwli">
                  <a href="{% url 'songwrytrapp:writer' writer.id %}">{{ writer.first_name }} {{ writer.last_name }}</a><div class="cwli_object">{{ writer.percentage }}%</div>
                  <div class="details-buttons">
                    <a href="{% url 'songwrytrapp:composition_writer_edit_form' composition.id writer.compositionwriter_id %}"><button class="edit_button"><img src="{% static "img/edit.png" %}" alt="Edit Composition Writer" height="16px" style="vertical-align:middle"></button></a>
                    <form class="compositionWriter" action="{% url 'songwrytrapp:composition_writer_remove' composition.id writer.compositionwriter_id %}" method="POST">
                      {% csrf_token %}
                      <input type="hidden" name="actual_method" value="DELETE">
                      <button class="plusminus_button"><img src="{% static "img/minus.png" %}" alt="Remove Writer" height="16px"></button>
                    </form>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
            <div class="cwli"><a href="{% url 'songwrytrapp:composition_writer_form' composition.id %}"><button class="plusminus_button"><img src="{% static "img/plus.png" %}" alt="Attach Writer" height="16px" style="vertical-align:middle"> ATTACH WRITER</button></a></div>
          </div>
        </div>
      </div>
    </div>
    <div class="wrap-collabsible">
      <input id="collapsible4" class="toggle" type="checkbox">
      <label for="collapsible4" class="lbl-toggle">Publishing Share</label>
      <div class="collapsible-content">
        <div class="content-inner">
          <div>
            {% for publishingcompany in composition_publishingcompanies %}
                {% if request.user.id == publishingcompany.user_id %}
                    <div class="cpcli">
                      <a href="{% url 'songwrytrapp:publishingcompany' publishingcompany.id %}">{{ publishingcompany.name }}</a><div class="cpcli_object">{{ publishingcompany.percentage }}%</div>{{ publishingcompany.pro }} Work ID: {{ publishingcompany.pro_work_num }}
                        <div class="details-buttons cpcli_object">
                          <a href="{% url 'songwrytrapp:composition_publishing_edit_form' composition.id publishingcompany.compositionpublishing_id %}"><button class="edit_button"><img src="{% static "img/edit.png" %}" alt="Edit Composition Publishing Company" height="16px" style="vertical-align:middle"></button></a>
                          <form class="compositionPublishing" action="{% url 'songwrytrapp:composition_publishing_remove' composition.id publishingcompany.compositionpublishing_id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="actual_method" value="DELETE">
                            <button class="plusminus_button"><img src="{% static "img/minus.png" %}" alt="Remove Publishing Company" height="16px"></button>
                          </form>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            <li class="cpcli"><a href="{% url 'songwrytrapp:composition_publishing_form' composition.id %}"><button class="plusminus_button"><img src="{% static "img/plus.png" %}" alt="Attach Publishing Company" height="16px" style="vertical-align:middle"> ATTACH PUBLISHING COMPANY</button></a></li>
          </div>
        </div>
      </div>
    </div>
    <div class="wrap-collabsible">
      <input id="collapsible5" class="toggle" type="checkbox">
      <label for="collapsible5" class="lbl-toggle">Recordings</label>
      <div class="collapsible-content">
        <div class="content-inner">
          <div style="list-style: none;">
            {% for recording in composition_recordings %}
                {% if request.user.id == recording.user_id %}
                    <div class="recli">
                      <div class="recording">
                        <div class="recording_columns">
                          <div class="left_column">
                            <div>
                              {% if recording.image_url %}
                                    <img src="{{ recording.image_url }}" class="recording_image">
                                {% else %}
                                    <img src="{% static "img/recording.png" %}" class="recording_image">
                                {% endif %}
                            </div>
                          </div>
                          <div class="right_column">
                            <div>
                              "{{ composition.title }}"
                            </div>
                            {% if recording.recording_type %}
                              <div>
                                Type: {{ recording.recording_type }}
                              </div>
                            {% endif %}
                            <div>Producer: {{ recording.producer }}</div>
                            <div>Artist: {{ recording.artist }}</div>
                            <div>Date Recorded: {{ recording.date_refactored }}</div>
                            <div>
                              {% if recording.is_mixed == "on" %}✅ Mixed | {% else %}❌ Not Mixed | {% endif %}{% if recording.is_mastered == "on" %}✅ Mastered | {% else %}❌ Not Mastered | {% endif %}{% if recording.is_delivered == "on" %}✅ Delivered{% else %}❌ Not Delivered{% endif %}
                            </div>
                          </div>
                        </div>
                        <div>
                          <audio controls id="player" controlsList="nodownload">
                            <source src="{{ recording.audio_url }}">
                            Your browser does not support the audio element.
                          </audio>
                        </div>
                      </div>
                      <div class="details-buttons">
                        <a href="{% url 'songwrytrapp:composition_recording_edit_form' composition.id recording.id %}"><button class="edit_button"><img src="{% static "img/edit.png" %}" alt="Edit Recording" height="16px" style="vertical-align:middle"> EDIT RECORDING</button></a>
                        <form class="compositionRecording" action="{% url 'songwrytrapp:composition_recording_delete' composition.id recording.id %}" method="POST" onsubmit="return ConfirmDeleteRecording()">
                          {% csrf_token %}
                          <input type="hidden" name="actual_method" value="DELETE">
                          <button class="plusminus_button"><img src="{% static "img/minus.png" %}" alt="Delete Recording" height="16px"> DELETE RECORDING </button>
                        </form>
                      </div>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="recli"><a href="{% url 'songwrytrapp:composition_recording_form' composition.id %}"><button class="plusminus_button"><img src="{% static "img/plus.png" %}" alt="Add Recording" height="16px" style="vertical-align:middle"> ADD RECORDING</button></a></li>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <h1>No composition exists with specified ID</h1>
  {% endif %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/delete.js' %}"></script>
{% endblock %}

songwrytrproject/songwrytrapp/templates/compositions/list.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/compositions.css' %}" />
{% endblock %}

{% block navbar %}
    {% if request.user.id %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'songwrytrapp:home'%}"><img src="{% static "img/songwrytr_logo_sm.png" %}" alt="SONGWRYTR" height="50px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songwrytrapp:writers' %}">Writers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'songwrytrapp:compositions' %}">Compositions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songwrytrapp:publishingcompanies' %}">Publishing</a>
                    </li>
                </ul>
                <a class="form-inline my-2 my-lg-0" href="{% url 'songwrytrapp:logout' %}">Logout</a>
            </div>
        </nav>
    {% endif %}
{% endblock %}

{% block content %}
    <a href="{% url 'songwrytrapp:composition_form' %}"><button class="plusminus_button margin-bottom-10"><img src="{% static "img/plus.png" %}" alt="Add Composition" height="32px" style="vertical-align:middle"> ADD COMPOSITION</button></a>
    {% if all_compositions %} <input type="text" id="myInput" onkeyup="search()" placeholder="Search for compositions or lyrics..."> {% endif %}
    <ol id="myOL">
        {% for composition in all_compositions %}
            {% if request.user.id == composition.user_id %}
                <li><a style="display: none">{{ composition.title }} {{ composition.alt_titles }} {{ composition.lyrics }} {{ composition.notes }}</a><a href="{% url 'songwrytrapp:composition' composition.id %}">"{{ composition.title }}"</a></li>
            {% endif %}
        {% endfor %}
    </ol>
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/search.js' %}"></script>
{% endblock %}

songwrytrproject/songwrytrapp/templates/compositions/publishing_form.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/compositions.css' %}" />
{% endblock %}

{% block navbar %}
    {% if request.user.id %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'songwrytrapp:home'%}"><img src="{% static "img/songwrytr_logo_sm.png" %}" alt="SONGWRYTR" height="50px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songwrytrapp:writers' %}">Writers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'songwrytrapp:compositions' %}">Compositions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songwrytrapp:publishingcompanies' %}">Publishing</a>
                    </li>
                </ul>
                <a class="form-inline my-2 my-lg-0" href="{% url 'songwrytrapp:logout' %}">Logout</a>
            </div>
        </nav>
    {% endif %}
{% endblock %}

{% block content %}
    {% if compositionpublishing.id is not None %}
        <h1>Update Publishing Company Share for "{{ composition.title }}"</h1>
        <form action="{% url 'songwrytrapp:composition_publishing_edit_form' composition.id compositionpublishing.id %}" method="post">
          <input type="hidden" name="actual_method" value="PUT">
    {% else %}
        <h1>Attach publishing company for "{{ composition.title }}"</h1>
        <form action="{% url 'songwrytrapp:composition_publishing_form' composition.id %}" method="post">
    {% endif %}
      {% csrf_token %}
      <fieldset>
          <label for="publishingcompany">Publishing Company: </label>
          <select id="publishingcompany" type="text" name="publishingcompany" required>
            <option value="" selected>Select Publishing Company</option>
            {% for publishingcompany in all_publishers %}
                {% if request.user.id == publishingcompany.user_id %}
                    <option value="{{ publishingcompany.id }}" {% if publishingcompany.id == compositionpublishing.publishing_company_id %}selected{% endif %}>{{ publishingcompany.name }}</option>
                {% endif %}
            {% endfor %}
          </select>
      </fieldset>
      <fieldset>
          <label for="percentage">Percentage: </label>
          <input id="percentage" type="number" name="percentage" step="0.01" min="0" max="{{totalpct}}" required value="{{ compositionpublishing.percentage }}">
      </fieldset>
      <fieldset>
          <label for="pro_work_num">PRO Work ID: </label>
          <input id="pro_work_num" type="text" name="pro_work_num" value="{{ compositionpublishing.pro_work_num }}">
      </fieldset>
      <input type="submit" value="Submit" />
    </form>
{% endblock %}